### ISSUE TITLE
Protótipo da Tela de Carregamento do App

### ISSUE THREAD

**Issue by crisfaria** [crisfaria/pi-iesb#29]
- [x] Mostrar na tela uma logo dinâmica para sinalizar ao usuário a abertura/carregamento do App. Deverá ser implementado no FIGMA e o link compartilhado por aqui.

**Comment by Odigo** [comment]
https://www.figma.com/file/d61SR2GMjtgjtcmAkh84nz/Untitled?type=design&node-id=0-1&mode=design&t=bqePVA2Zjy3j4kwN-0
