### ISSUE TITLE
Protótipo da Tela de Login/Signup

### ISSUE THREAD

**Issue by crisfaria** [crisfaria/pi-iesb#32]
- [x] Permite ao usuário logar no perfil através de email cadastrado e senha ou realizar o cadastro de perfil no App. Deverá ser implementado no Figma e o link compartilhado aqui.

**Comment by Odigo** [comment]
https://www.figma.com/file/d61SR2GMjtgjtcmAkh84nz/Untitled?type=design&node-id=0-1&mode=design&t=6dbZGd8RXJ0HlTlX-0
