### ISSUE TITLE
Protótipo da Tela de Registro de Alimentos

### ISSUE THREAD

**Issue by crisfaria** [crisfaria/pi-iesb#49]
Deverá ser implementada no FIGMA e seu link compartilhado aqui, e conter as seguintes funcionalidades:

- [x] Permitir que os usuários registrem os alimentos que consumiram ao longo do dia, incluindo nome do alimento, quantidade, horário e refeição (café da manhã, almoço, jantar, lanches).

- [x] Incluir uma função de busca para facilitar a adição de alimentos ao diário. Isso pode ser feito através de uma lista de alimentos pré-cadastrados ou através de uma integração com uma base de dados de alimentos.

- [x] Anotações e Emoções: 
    - [x] Oferecer um espaço para os usuários adicionarem reações sobre suas refeições, como se sentiram durante ou após a refeição.
- [x] Lembretes e Notificações: 
   - [x] Oferecer a opção de definir lembretes para registrar refeições ou para acompanhar o progresso em direção às metas.

**Comment by SamotX** [comment]
![Image](https://github.com/crisfaria/pi-iesb/assets/77175507/d46497cf-79f1-448a-80cc-9c106048d6b2)

**Comment by SamotX** [comment]
Link Figma: https://www.figma.com/file/d61SR2GMjtgjtcmAkh84nz/Untitled?type=design&node-id=0%3A1&mode=design&t=I1tvX9JC85k7PQdv-1

**Comment by SamotX** [comment]
![Image](https://github.com/crisfaria/pi-iesb/assets/77175507/a779ef58-393d-45ff-b22e-ab2bb40398d8)
